#schema.yml
version: 2
sources:
  - name: gz_raw_data                 # Kaynak adı (örnek)
    schema: gz_raw_data         # Warehouse içindeki şema adı
    tables:
      - name: raw_gz_sales            # Tablo adı
      - name: raw_gz_product
      - name: raw_gz_ship